# Generated by Django 4.2.7 on 2024-02-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("working_areas", models.TextField(blank=True)),
                ("total_budget", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("ongoing", "Ongoing"), ("completed", "Completed")],
                        default="ongoing",
                        max_length=10,
                    ),
                ),
                ("photos", models.ImageField(upload_to="photos/")),
                ("videos", models.FileField(blank=True, upload_to="media/videos/")),
                ("description", models.TextField(blank=True)),
                ("partners", models.CharField(max_length=255)),
                ("partners_logo", models.ImageField(upload_to="media/logos/")),
                (
                    "project_document",
                    models.FileField(
                        blank=True, null=True, upload_to="media/Project/documents/"
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("starting_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
    ]
