# Generated by Django 4.2.7 on 2024-02-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="partners_logo",
            field=models.ImageField(upload_to="Partner/logos"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="photos",
            field=models.ImageField(upload_to="Project/photos"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="project_document",
            field=models.FileField(
                blank=True, null=True, upload_to="Project/documents"
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="videos",
            field=models.FileField(blank=True, upload_to="Project/videos"),
        ),
    ]
