# Generated by Django 4.2.7 on 2024-02-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_alter_projects_partners_logo_alter_projects_photos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="Announcements/image")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="Announcements/files/"
                    ),
                ),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
